services:
  # 1. Servicio de la API (NestJS)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres_db
      - redis_cache

  # 2. Servicio de la Base de Datos (PostgreSQL)
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. Servicio de Caché / Mensajería (Redis)
  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    volumes:
      - redis_data:/data

# Definimos volúmenes nombrados para que los datos no se borren al apagar los contenedores
volumes:
  postgres_data:
  redis_data:
